services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tulook_api
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=tulook_db
      - DB_USERNAME=tulook_api
      - DB_PASSWORD=Encantoparatodos
    depends_on: 
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Encantoparatodos
      MYSQL_DATABASE: tulook_db
      MYSQL_USER: tulook_api
      MYSQL_PASSWORD: Encantoparatodos
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: tulook_api
      PMA_PASSWORD: Encantoparatodos
    depends_on:
      - mysql
