networks:
  tulook:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tulook_api
    ports:
      - 8000:80
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=tulook_db
      - DB_USERNAME=tulook_api
      - DB_PASSWORD=Encantoparatodos
    depends_on:
      - mysql
    networks:
      - tulook

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - tulook
    environment:
      - MYSQL_ROOT_PASSWORD=Encantoparatodos
      - MYSQL_DATABASE=tulook_db
      - MYSQL_USER=tulook_api
      - MYSQL_PASSWORD=Encantoparatodos
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - tulook
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=tulook_api
      - PMA_PASSWORD=Encantoparatodos
    depends_on:
      - mysql