# Generated by Django 5.1 on 2024-08-16 13:46

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'prestaciones',
            },
        ),
        migrations.CreateModel(
            name='ProfesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'profesiones',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('detalles', models.TextField(max_length=500)),
                ('ubicacion', models.TextField(blank=True, max_length=500, null=True)),
                ('horario', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='Servicio_has_prestaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestaciones_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='encantoAPI.prestaciones')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='encantoAPI.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('numContacto', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CR', unique=True, verbose_name='teléfono')),
                ('isContactPublico', models.IntegerField(default=0, verbose_name='¿El contacto es público?')),
                ('isActive', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Último inicio de sesión')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='encantoAPI.profesionusuario')),
                ('tipoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='encantoAPI.tipocuenta')),
            ],
            options={
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='encantoAPI.usuario'),
        ),
    ]
