# Generated by Django 5.1 on 2024-08-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encantoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio_has_prestaciones',
            old_name='prestaciones_id',
            new_name='prestaciones',
        ),
        migrations.RenameField(
            model_name='servicio_has_prestaciones',
            old_name='servicio_id',
            new_name='servicio',
        ),
    ]
